import 'styled-components'

declare module 'styled-components' {
  export interface DefaultTheme {
    colors: {
      primary: {
        lightest: string,
        light: string,
        pure: string,
        dark: string,
        darkest: string,
      },
      secondary: {
        lightest: string,
        light: string,
        pure: string,
        dark: string,
        darkest: string,
      },
      tertiary: {
        lightest: string,
        light: string,
        pure: string,
        dark: string,
        darkest: string,
      },
      success: {
        lightest: string,
        light: string,
        pure: string,
        dark: string,
        darkest: string,
      },
      error: {
        lightest: string,
        light: string,
        pure: string,
        dark: string,
        darkest: string,
      },
      alert: {
        lightest: string,
        light: string,
        pure: string,
        dark: string,
        darkest: string,
      },
      info: {
        lightest: string,
        light: string,
        pure: string,
        dark: string,
        darkest: string,
      },
      high: {
        pure: string,
        light: string,
        medium: string,
        dark: string,
        darkest: string,
      },
      low: {
        pure: string,
        dark: string,
        medium: string,
        light: string,
        lightest: string,
      },
      shadow: string
    },
    font: {
      weight: {
        tiny: number,
        regular: number,
        bold: number,
      },
    },
    sizes: {
      "2px": string,
      "4px": string,
      "6px": string,
      "8px": string,
      "12px": string,
      "16px": string,
      "20px": string,
      "24px": string,
      "28px": string,
      "32px": string,
      "36px": string,
      "40px": string,
      "44px": string,
      "48px": string,
      "52px": string,
      "56px": string,
      "60px": string,
      "64px": string,
      "68px": string,
      "72px": string,
      "76px": string,
      "80px": string,
      "84px": string,
      "88px": string,
      "92px": string,
      "96px": string,
      "108px": string,
      "136px": string,
      "140px": string,
      "144px": string,
      "160px": string,
      "176px": string,
      "212px": string,
      "236px": string,
      "256px": string,
      "260px": string,
      "288px": string,
      "320px": string,
      "408px": string,
      "656px": string,
    },
  }
}